import { AppointmentTypeRule } from "@/schemas/appointment";

export const APPOINTMENT_TYPES_DETAIL: AppointmentTypeRule[] = [
  {
    id: "new-patient",
    type: "new-patient",
    name: "ผู้ป่วยใหม่",
    duration: 60,
    buffer: 10,
    color: "bg-violet-100 text-violet-800 border-violet-200",
    colorHex: "#7c3aed",
    icon: "👤",
    advanceBookingMin: 24,
    advanceBookingMax: 90,
    requiresPriorVisit: false,
    requiresConsentForm: false,
    requiresRoom: false,
    allowSameDayBooking: false,
    sameDocOnly: false,
    description:
      "การนัดหมายครั้งแรกสำหรับผู้ป่วยที่ไม่เคยมาพบแพทย์มาก่อน ประกอบด้วยการซักประวัติทางการแพทย์อย่างละเอียด การตรวจร่างกายเบื้องต้น และการวางแผนการดูแลรักษา",
    rules: [
      "ต้องจองล่วงหน้าอย่างน้อย 24 ชั่วโมง",
      "ผู้ป่วยต้องมาถึงก่อนเวลานัด 15 นาทีเพื่อกรอกเอกสาร",
      "ต้องมีการสร้างประวัติผู้ป่วยก่อนหรือระหว่างการจอง",
      "ไม่สามารถจองในวันเดียวกันได้",
    ],
  },
  {
    id: "follow-up",
    type: "follow-up",
    name: "ติดตามอาการ",
    duration: 20,
    buffer: 5,
    color: "bg-blue-100 text-blue-800 border-blue-200",
    colorHex: "#2563eb",
    icon: "🔁",
    advanceBookingMin: 0,
    advanceBookingMax: 60,
    requiresPriorVisit: true,
    requiresConsentForm: false,
    requiresRoom: false,
    allowSameDayBooking: true,
    sameDocOnly: true,
    description:
      "การนัดติดตามผลหลังจากการรักษาหรือการพบแพทย์ครั้งก่อน เพื่อตรวจสอบอาการ ความคืบหน้า และปรับแผนการรักษา",
    rules: [
      "ต้องอ้างอิงการนัดหมายครั้งก่อนในระบบ",
      "ต้องนัดกับแพทย์คนเดิมเท่านั้น",
      "สามารถจองภายในวันเดียวกันได้",
      "จองล่วงหน้าได้สูงสุด 60 วัน",
    ],
  },
  {
    id: "consultation",
    type: "consultation",
    name: "ปรึกษาแพทย์",
    duration: 30,
    buffer: 5,
    color: "bg-emerald-100 text-emerald-800 border-emerald-200",
    colorHex: "#059669",
    icon: "💬",
    advanceBookingMin: 0,
    advanceBookingMax: 90,
    requiresPriorVisit: false,
    requiresConsentForm: false,
    requiresRoom: false,
    allowSameDayBooking: true,
    sameDocOnly: false,
    description:
      "การเข้าพบแพทย์เพื่อขอคำปรึกษา อาจเป็นการส่งต่อจากแพทย์ท่านอื่นหรือผู้ป่วยนัดเอง สามารถเลือกแพทย์หรือแผนกใดก็ได้",
    rules: [
      "ไม่มีข้อจำกัดเรื่องแพทย์ สามารถเลือกแพทย์ที่ว่างได้",
      "สามารถแนบใบส่งตัวจากแพทย์ได้",
      "สามารถจองในวันเดียวกันได้",
      "สามารถนัดข้ามแผนกได้",
    ],
  },
  {
    id: "procedure",
    type: "procedure",
    name: "หัตถการ / การทำหัตถการ",
    duration: 90,
    buffer: 15,
    color: "bg-amber-100 text-amber-800 border-amber-200",
    colorHex: "#d97706",
    icon: "🔬",
    advanceBookingMin: 48,
    advanceBookingMax: 60,
    requiresPriorVisit: false,
    requiresConsentForm: true,
    requiresRoom: true,
    allowSameDayBooking: false,
    sameDocOnly: false,
    description:
      "การรักษาหรือหัตถการทางการแพทย์ที่ต้องใช้ห้อง อุปกรณ์ และเวลาเตรียมการเฉพาะ อาจต้องมีพยาบาลหรือผู้ช่วยร่วมดูแล",
    rules: [
      "ต้องจองล่วงหน้าอย่างน้อย 48 ชั่วโมง",
      "ต้องมีการลงนามใบยินยอมก่อนวันนัด",
      "ต้องมีการกำหนดห้องหัตถการตั้งแต่ตอนจอง",
      "ไม่สามารถนัดติดกันได้ ต้องเว้น buffer time",
      "อาจต้องมีพยาบาลหรือผู้ช่วยประจำหัตถการ",
    ],
  },
];
